### ISSUE TITLE
SQLite3 module issues

### ISSUE THREAD

**Issue by mkBlaze** [CamHenlin/imessageclient#7]
When I try to launch the application, I am told about how some SQLite3 nodes/modules can't be found. I can see them in Finder, so I know they are there.

Kyles-Air:imessageclient Kyle$ node app
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Kyle/imessageclient/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by CamHenlin** [comment]
Interesting, what happens if you type npm install and try running again?

**Comment by mkBlaze** [comment]
Same thing.

Kyles-Air:imessageclient Kyle$ npm install
npm WARN package.json imessageninja_fullclient@1.0.0 No repository field.
npm WARN package.json applescript@1.0.0 No repository field.
express@4.11.2 node_modules/express
├── utils-merge@1.0.0
├── merge-descriptors@0.0.2
├── methods@1.1.1
├── fresh@0.2.4
├── cookie@0.1.2
├── escape-html@1.0.1
├── range-parser@1.0.2
├── cookie-signature@1.0.5
├── finalhandler@0.3.3
├── vary@1.0.0
├── media-typer@0.3.0
├── parseurl@1.3.0
├── serve-static@1.8.1
├── content-disposition@0.5.0
├── path-to-regexp@0.1.3
├── depd@1.0.0
├── qs@2.3.3
├── debug@2.1.1 (ms@0.6.2)
├── on-finished@2.2.0 (ee-first@1.1.0)
├── send@0.11.1 (destroy@1.0.3, ms@0.7.0, mime@1.2.11)
├── etag@1.5.1 (crc@3.2.1)
├── proxy-addr@1.0.6 (forwarded@0.1.0, ipaddr.js@0.1.8)
├── type-is@1.5.6 (mime-types@2.0.8)
└── accepts@1.2.3 (negotiator@0.5.0, mime-types@2.0.8)
Kyles-Air:imessageclient Kyle$ node app
module.js:338
    throw err;
          ^
Error: Cannot find module '/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/Kyle/imessageclient/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)

**Comment by CamHenlin** [comment]
I believe I have fixed this in the latest version. You'll need to re-pull, npm install, then try running. I believe this was a problem with node gyp and the prebuilt code in the repo, which is now gone

**Comment by mkBlaze** [comment]
Still not working, does this require Xcode or Xcode command line tools? I believe I have the command line tools installed but not Xcode. Not sure if that makes a difference or not.

**Comment by CamHenlin** [comment]
Does it look like this when you try installing:
```
Camerons-MacBook-Air:imessageclient camh$ npm install
npm WARN package.json imessageclient@1.0.0 No repository field.
/
> sqlite3@3.0.4 install /Users/camh/Documents/imessageclient/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

[sqlite3] Success: "/Users/camh/Documents/imessageclient/node_modules/sqlite3/lib/binding/node-v11-darwin-x64/node_sqlite3.node" is installed via remote
beepbeep@1.2.0 node_modules/beepbeep

exec@0.1.3 node_modules/exec

applescript@1.0.0 node_modules/applescript

blessed@0.0.43 node_modules/blessed

sqlite3@3.0.4 node_modules/sqlite3
└── nan@1.4.3
```

**Comment by mkBlaze** [comment]
Nope.

Kyles-Air:imessageclient Kyle$ npm install
npm WARN package.json imessageninja_fullclient@1.0.0 No repository field.
-
> sqlite3@3.0.4 install /Users/Kyle/imessageclient/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

xcode-select: error: tool 'xcodebuild' requires Xcode, but active developer directory '/Library/Developer/CommandLineTools' is a command line tools instance

  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c:8645:26: warning: unused
      variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings and 2 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/Kyle/imessageclient/node_modules/sqlite3
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Kyle/imessageclient/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/Kyle/imessageclient/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Kyle/imessageclient/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Kyle/imessageclient/npm-debug.log

Suppose I should also give you that log. Uploaded it here http://puu.sh/fD5S7.txt

**Comment by CamHenlin** [comment]
Alright, looks like my dependency on sqlite3 requires node-gyp, which requires command line tools. You'll need to follow instructions here: https://github.com/TooTallNate/node-gyp to get node-gyp, then try npm install again in the iMessage client. Sorry for the hassle!

**Comment by mkBlaze** [comment]
Installed node-gyp, however I am still getting errors when running npm install in the imessageclient directory.

Kyles-Air:imessageclient Kyle$ npm install
npm WARN package.json imessageclient@1.0.0 No repository field.
-
> sqlite3@3.0.4 install /Users/Kyle/imessageclient/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

child_process: customFds option is deprecated, use stdio instead.
  ACTION deps_sqlite3_gyp_action_before_build_target_unpack_sqlite_dep Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c
  TOUCH Release/obj.target/deps/action_before_build.stamp
  CC(target) Release/obj.target/sqlite3/gen/sqlite-autoconf-3080701/sqlite3.o
Release/obj/gen/sqlite-autoconf-3080701/sqlite3.c:8645:26: warning: unused
      variable 'sqlite3one' [-Wunused-const-variable]
SQLITE_PRIVATE const int sqlite3one = 1;
                         ^
1 warning generated.
  LIBTOOL-STATIC Release/sqlite3.a
  CXX(target) Release/obj.target/node_sqlite3/src/database.o
../src/database.cc:134:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("filename"), args[0]->ToString(), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:135:18: error: no matching member function for call to 'Set'
    args.This()->Set(NanNew("mode"), NanNew<Integer>(mode), ReadOnly);
    ~~~~~~~~~~~~~^~~
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2112:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(Handle<Value> key, Handle<Value> value);
       ^
/Users/Kyle/.node-gyp/0.12.0/deps/v8/include/v8.h:2114:8: note: candidate
      function not viable: requires 2 arguments, but 3 were provided
  bool Set(uint32_t index, Handle<Value> value);
       ^
../src/database.cc:145:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:230:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:509:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
../src/database.cc:610:9: warning: unused variable 'status' [-Wunused-variable]
    int status = uv_queue_work(uv_default_loop(),
        ^
4 warnings and 2 errors generated.
make: *** [Release/obj.target/node_sqlite3/src/database.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--name=sqlite3" "--configuration=Release" "--module_name=node_sqlite3" "--version=3.0.4" "--major=3" "--patch=4" "--runtime=node" "--node_abi=node-v14" "--platform=darwin" "--target_platform=darwin" "--arch=x64" "--target_arch=x64" "--module_main=./lib/sqlite3" "--host=https://mapbox-node-binary.s3.amazonaws.com/" "--module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64" "--module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node" "--remote_path=./sqlite3/v3.0.4/" "--package_name=node-v14-darwin-x64.tar.gz" "--staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz" "--hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/" "--hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz"
gyp ERR! cwd /Users/Kyle/imessageclient/node_modules/sqlite3
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok 
node-pre-gyp ERR! build error 
node-pre-gyp ERR! stack Error: Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/Users/Kyle/imessageclient/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/compile.js:76:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
node-pre-gyp ERR! stack     at maybeClose (child_process.js:1008:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1080:5)
node-pre-gyp ERR! System Darwin 14.1.0
node-pre-gyp ERR! command "node" "/Users/Kyle/imessageclient/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/Kyle/imessageclient/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.1
node-pre-gyp ERR! not ok 
Failed to execute '/usr/local/bin/node /usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js rebuild --name=sqlite3 --configuration=Release --module_name=node_sqlite3 --version=3.0.4 --major=3 --patch=4 --runtime=node --node_abi=node-v14 --platform=darwin --target_platform=darwin --arch=x64 --target_arch=x64 --module_main=./lib/sqlite3 --host=https://mapbox-node-binary.s3.amazonaws.com/ --module_path=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64 --module=/Users/Kyle/imessageclient/node_modules/sqlite3/lib/binding/node-v14-darwin-x64/node_sqlite3.node --remote_path=./sqlite3/v3.0.4/ --package_name=node-v14-darwin-x64.tar.gz --staged_tarball=build/stage/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz --hosted_path=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/ --hosted_tarball=https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v3.0.4/node-v14-darwin-x64.tar.gz' (1)
npm ERR! Darwin 14.1.0
npm ERR! argv "node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! sqlite3@3.0.4 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sqlite3@3.0.4 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/Kyle/imessageclient/npm-debug.log

**Comment by CamHenlin** [comment]
I really hate to blame the user here because I want to help you, but this really seems like an issue with your nodejs installation to me. Unfortunately, I have the feeling that just typing "npm install sqlite3" on your system will throw an error, which you'll probably want to confirm. How do you have node installed? I have one of my computers installed via homebrew and the other installed via the nodejs.org installer and both of those seem to work.

**Comment by mkBlaze** [comment]
I've figured that it has to do with my NodeJS installation at this point. I was looking here https://www.npmjs.com/package/sqlite3 and noticed that it says that SQLite3 only supports NodeJS versions 0.10.x and 0.11.x and I had 0.12, could this be the problem? What versions are you running?

**Comment by CamHenlin** [comment]
I am running v0.10.35 on both of my systems

**Comment by mkBlaze** [comment]
That was it, I've got it running now, thanks for your help.
